language: python
dist: xenial
python:
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get install -y python3-tk
  - sudo apt-get install -y texlive-latex-base pgf texlive-pictures texlive-latex-extra
  - sudo apt-get install -y libblas-dev liblapack-dev libatlas-base-dev gfortran
install:
  - pip3 install --editable ".[dev]"
script:
  - python manage.py test
after_success:
  - coverage run --source=survey --omit=survey/migrations/* ./manage.py test
  - coverage html
  - coveralls
